<a href="https://colab.research.google.com/github/GOVINDFROMINDIA/PYTHON-FOR-DATA-SCIENCE/blob/main/NUMPY_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
from numpy.core.fromnumeric import shape
!pip install numpy
import numpy as np
my_list=[(1,2,3,4,5,6,7,8,9,10),(10,20,30,40,50,60,70,80,90,100)]
array = np.array(my_list, dtype =int)
print(array)

print(type(array))
print(len(array))
print(array.ndim)
print(array.shape)

array2= array.reshape(4,5)
print(array2)
print(array2.shape)

array3= array.reshape(1,-1)  #-1 is used if other thing is unknown
print(array3)
print(array3.shape) 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
[[  1   2   3   4   5   6   7   8   9  10]
 [ 10  20  30  40  50  60  70  80  90 100]]
<class 'numpy.ndarray'>
2
2
(2, 10)
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 10  20  30  40  50]
 [ 60  70  80  90 100]]
(4, 5)
[[  1   2   3   4   5   6   7   8   9  10  10  20  30  40  50  60  70  80
   90 100]]
(1, 20)
