<a href="https://colab.research.google.com/github/GOVINDFROMINDIA/PYTHON-FOR-DATA-SCIENCE/blob/main/NUMPY_multi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr1=[1,2,3]
arr2=[4,5,6]
arr3=[7,8,9]
mul_arr = np.array([arr1,arr2,arr3])
print(mul_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
